I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script call
    'Suddenly you notice another thing'
  File "renpy/common/00console.rpy", line 1171, in script call
    python in _console:
NameError: name 'test' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 15, in script call
    'Suddenly you notice another thing'
  File "renpy/common/00console.rpy", line 1171, in script call
    python in _console:
  File "<string>", line 1, in script
  File "C:\Users\Seb\Desktop\Renpy\renpy-8.2.3-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Seb\Desktop\Renpy\renpy-8.2.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "<string>", line 1, in <module>
NameError: name 'test' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
Branching_Test 1.0
Sun Aug 18 15:46:00 2024
